### ISSUE TITLE
Deserialization perf for partial response objects

### ISSUE THREAD

**Issue by tadeuszwojcik** [Tornhoof/SpanJson#105]
Hi,
I was wondering if there is anything that could speed up deserialization when my deserialized object contains only some of the properties of json object or when JSON object has an array of objects and I'm only interested in one out of 10 properties of objects in such array?

**Comment by Tornhoof** [comment]
Hello,
No, there are no built-in ways to do that.
Depending how partial the response is, a custom serializer type might help, e.g. a custom list formatter which skips the deserialization after 10 elements. For any complex type that gets really complicated really fast though.

**Comment by tadeuszwojcik** [comment]
I see, thanks for quick reply. Do you think such optimization would bring measurable benefits? For example for json that has an array with 10 elements each of them 5 fields, but only 2 of them would be deserialized.
I guess the only savings here would be that there is no need to convert byte array/span to numbers/strings for not needed fields? Whole json needs to be parsed anyway...

**Comment by Tornhoof** [comment]
Generally speaking, there are 3 bigger performance aspects:
- parsing the JSON structure
- parsing the JSON value
- assignment of the correct field/property

As you've said, you need to parse anyway. The other two parts take quite a bit of time too, especially If you have many fields in your type or large string values. 

For your specific example and specifically that array ratio, it could help if your fields are large strings or similar types. In general your custom formatter needs to be very efficient (that's why the array example works, after 2 fully deserialized entries you just call skip). 

Personally, I wouldn't bother, if a few microseconds , and that's probably the gain we're talking about, is enough to justify such measures, then either your codebase is already extremely well optimized or you should look elsewhere in your code.

**Comment by tadeuszwojcik** [comment]
All makes sense, thanks again!
