### ISSUE TITLE
Redundant quotes, when deserializing dictionary

### ISSUE THREAD

**Issue by dimaaan** [Tornhoof/SpanJson#77]
Example:
```csarp
JsonSerializer.Generic.Utf8.Deserialize<Dictionary<string, object>>(System.Text.Encoding.UTF8.GetBytes(@"{""a"": ""1""}"))["a"].ToString();
```
Expected result:
"1"
Actual result:
"\\"1\\""

**Comment by Tornhoof** [comment]
You assume in your code, that the value in the dictionary is a string, but it's not. It's a dynamic object, because your trying to deserialize Into an untyped object.
The easiest way to handle this, is to cast the value to dynamic and then to string.
Example: https://github.com/Tornhoof/SpanJson/blob/186d1d36e376dcfca67298bf3d1f71d3e063fbef/SpanJson.Tests/DictionaryTests.cs#L321-L327

**Comment by Tornhoof** [comment]
I'll look into how to improve this behaviour.

**Comment by Tornhoof** [comment]
I changed the ``ToString()`` behaviour and added explicit operator overload for casts for the primitive types, so going through dynamic should not be necessary in many cases. This will be part of the 2.0 release.
