### ISSUE TITLE
[question] Working with enums

### ISSUE THREAD

**Issue by tadeuszwojcik** [Tornhoof/SpanJson#94]
Hi,
First of all, thanks for open sourcing this lib, works great (it's really fast)!
I've got couple of questions regarding deserializing enums.
When deserializing from enum to string, would it be possible to deserialize from camelCase strings as well, even when enum is PascalCase? Currently I'm using `EnumMember` , but was wondering if there is a different way (like in case of camelCaseResolvers).

Another thing I'd like to ask is about deserializing to enum when string value doesn't match any (unknown enum value currently throws). In my use case I know all enum values, but it's a constant stream of data that may introduce new enum value which will currently break my deserialization logic. Would writing custom resolver for that be the best way? I'd like to map such unknown value to `default(myenum).`
Thanks!

**Comment by Tornhoof** [comment]
Hello,
No at the moment EnumMember is the best way for that, camelCaseResolver does change enums, I never  thought about that. 
As for a default(Enum), the easiest way is ICustomFormatter and annotate your types with it.
Take a look at https://github.com/Tornhoof/SpanJson/blob/b16e08fcd64cdf7dc5e0fdbb3ecbffe383d376bc/SpanJson.Tests/CustomSerializerTests.cs#L85-L122
basically it's the same, but instead of long.TryParse in Deserialize you could Enum.TryParse(...) and if that fails assign your default (instead of throw like in the example above) and in Serialize I'd simply call the EnumStringFormatter (instead of StringFormatter)

**Comment by tadeuszwojcik** [comment]
Great, Thank you! I'll try ICustomFormatter .
